version: '3'

services:

#  just-order-api:
#    build: ./api
#    ports:
#      - 3001:3001
#    volumes:
#      - ./api:/opt/app
#    networks:
#      - justordernet
#    depends_on:
#      - just-order-mongo

  just-order-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - justordernet
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s

  just-order-web:
      build: .
      ports:
        - 3000:3000
      volumes:
        - .:/opt/app
      networks:
        - justordernet
      depends_on:
        - just-order-mongo

networks:
  justordernet: