version: '3'

services:

  just-order-api:
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/opt/app
    networks:
      - justordernet
    depends_on:
      - just-order-mongo

  just-order-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - justordernet

  just-order-web:
      build: ./web
      ports:
        - 3000:3000
      volumes:
        - ./web:/opt/app
      networks:
        - justordernet

networks:
  justordernet: