version: '3'

services:

#  api:
#    build: ./api
#    ports:
#      - 3001:3000
#    volumes:
#      - ./api:/opt/app
#    networks:
#      - api
#    depends_on:
#      - mongo
#
#  mongo:
#    image: mongo
#    volumes:
#      - ./data:/data/db
#    networks:
#      - api

  just-order-web:
      build: ./web
      ports:
        - 3000:3000
      volumes:
        - ./web:/opt/app
      networks:
        - api

networks:
  api: